version: "3"
# clear all data, volumes, containers:
# docker-compose up -d zum starten
#  docker-compose stop
#  docker-compose rm
#  docker volume rm compositebuilder_postgresql compositebuilder_postgresql_data compositebuilder_sonarqube_data compositebuilder_sonarqube_extensions compositebuilder_sonarqube_logs compositebuilder_jenkins_data
services:
  jenkins:
    image: jenkins/jenkins:latest-jdk11
    ports:
      - "8888:8080"
    networks:
      - sonarnet
    volumes:
      - jenkins_data:/var/jenkins_home

  sonarqube:
    image: sonarqube:8.9-community
    depends_on:
      - db
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      # docker volume definitions (named volume with local driver)
      # managed by docker, reassigned on container restart without data loss
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres:13
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
